#!/usr/bin/env bash

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r hcv$i/trueData/hcvTrueMSA.fasta -e hcv$i/MAFFT/MAFFT.aln | grep Compression | sed 's/Compression//' >> MAFFTCompression
done

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r hcv$i/trueData/hcvTrueMSA.fasta -e hcv$i/MUSCLE/MUSCLE.aln | grep Compression | sed 's/Compression//' >> MUSCLECompression
done

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r hcv$i/trueData/hcvTrueMSA.fasta -e hcv$i/ClustalOmega/Clustal.aln | grep Compression | sed 's/Compression//' >> ClustalCompression
done
