#!/usr/bin/env bash

for ((i=0; i < 10; i++))
do
    cd hcv$i/MAFFT/FastTree
    mkdir IQTree IQTreeMFP PhyML RAxML 

    cd IQTree
    cp ../../../trueData/hcvTrueMSA.fasta .
    iqtree -m GTR+I+R -s hcvTrueMSA.fasta -nt AUTO -te ../fast.tre

    cd ../IQTreeMFP
    cp ../../../trueData/hcvTrueMSA.fasta .
    iqtree -m MFP -s hcvTrueMSA.fasta -nt AUTO -te ../fast.tre

    cd ../RAxML
    cp ../../../trueData/hcvTrueMSA.fasta .
    cat ../fast.tre | resolve_random.py > resolved.tre
    raxml-ng --msa hcvTrueMSA.fasta --model GTR+I+G --evaluate --tree resolved.tre

    cd ../PhyML
    cp ../../../trueData/hcvTrueMSA.phy .
    cat ../fast.tre | resolve_random.py > resolved.tre
    phyml -i hcvTrueMSA.phy -a e -d nt -m GTR --no_memory_check -o lr -u resolved.tre

    cd ../../../../
done
for ((i=0; i < 10; i++))
do
    cd hcv$i/MUSCLE/FastTree
    mkdir IQTree IQTreeMFP PhyML RAxML 

    cd IQTree
    cp ../../../trueData/hcvTrueMSA.fasta .
    iqtree -m GTR+I+R -s hcvTrueMSA.fasta -nt AUTO -te ../fast.tre

    cd ../IQTreeMFP
    cp ../../../trueData/hcvTrueMSA.fasta .
    iqtree -m MFP -s hcvTrueMSA.fasta -nt AUTO -te ../fast.tre

    cd ../RAxML
    cp ../../../trueData/hcvTrueMSA.fasta .
    cat ../fast.tre | resolve_random.py > resolved.tre
    raxml-ng --msa hcvTrueMSA.fasta --model GTR+I+G --evaluate --tree resolved.tre

    cd ../PhyML
    cp ../../../trueData/hcvTrueMSA.phy .
    cat ../fast.tre | resolve_random.py > resolved.tre
    phyml -i hcvTrueMSA.phy -a e -d nt -m GTR --no_memory_check -o lr -u resolved.tre

    cd ../../../../
done
for ((i=0; i < 10; i++))
do
    cd hcv$i/ClustalOmega/FastTree
    mkdir IQTree IQTreeMFP PhyML RAxML 

    cd IQTree
    cp ../../../trueData/hcvTrueMSA.fasta .
    iqtree -m GTR+I+R -s hcvTrueMSA.fasta -nt AUTO -te ../fast.tre

    cd ../IQTreeMFP
    cp ../../../trueData/hcvTrueMSA.fasta .
    iqtree -m MFP -s hcvTrueMSA.fasta -nt AUTO -te ../fast.tre

    cd ../RAxML
    cp ../../../trueData/hcvTrueMSA.fasta .
    cat ../fast.tre | resolve_random.py > resolved.tre
    raxml-ng --msa hcvTrueMSA.fasta --model GTR+I+G --evaluate --tree resolved.tre

    cd ../PhyML
    cp ../../../trueData/hcvTrueMSA.phy .
    cat ../fast.tre | resolve_random.py > resolved.tre
    phyml -i hcvTrueMSA.phy -a e -d nt -m GTR --no_memory_check -o lr -u resolved.tre

    cd ../../../../
done
