#!/usr/bin/env bash

for ((i=2; i < 10; i++))
do
    cd hcv$i/IQTreeMFP
    rm *
    cp ../trueData/hcvTrueMSA.fasta .
    iqtree -m MFP -s hcvTrueMSA.fasta -nt AUTO

    cd ../MAFFT/IQTreeMFP
    rm *
    cp ../MAFFT.aln .
    iqtree -m MFP -s MAFFT.aln -nt AUTO

    cd ../../ClustalOmega/IQTreeMFP
    rm *
    cp ../Clustal.aln .
    iqtree -m MFP -s Clustal.aln -nt AUTO

    cd ../../MUSCLE/IQTreeMFP
    rm *
    cp ../MUSCLE.aln .
    iqtree -m MFP -s MUSCLE.aln -nt AUTO

    cd ../../../
done
