#!/usr/bin/env bash

for ((i=0; i < 10; i++))
do
    cd hcv$i/FastTree
    cat ../trueData/hcvTrueMSA.fasta | FastTree -gamma -nt -gtr -out fast.tre

    cd ../IQTree
    cp ../trueData/hcvTrueMSA.fasta .
    iqtree -m GTR+I+R -s hcvTrueMSA.fasta -nt AUTO

    cd ../IQTreeMFP
    cp ../trueData/hcvTrueMSA.fasta .
    iqtree -m MFT -s hcvTrueMSA.fasta -nt AUTO

    cd ../RAxML
    cp ../trueData/hcvTrueMSA.fasta .
    raxml-ng --msa hcvTrueMSA.fasta --model GTR+I+G

    cd ../PhyML
    cp ../trueData/hcvTrueMSA.phy .
    phyml -i hcvTrueMSA.phy -a e -d nt -m GTR --no_memory_check

    cd ../../
done
