#!/usr/bin/env bash

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r ebola$i/trueData/ebolaTrueMSA.fasta -e ebola$i/MAFFT/MAFFT.aln | grep TC | sed 's/TC//' >> MAFFTTC
done

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r ebola$i/trueData/ebolaTrueMSA.fasta -e ebola$i/MUSCLE/MUSCLE.aln | grep TC | sed 's/TC//' >> MUSCLETC
done

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r ebola$i/trueData/ebolaTrueMSA.fasta -e ebola$i/ClustalOmega/Clustal.aln | grep TC | sed 's/TC//' >> ClustalTC
done
