#!/usr/bin/env bash

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r ebola$i/trueData/ebolaTrueMSA.fasta -e ebola$i/MAFFT/MAFFT.aln | grep Modeler | sed 's/Modeler//' >> MAFFTModeler
done

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r ebola$i/trueData/ebolaTrueMSA.fasta -e ebola$i/MUSCLE/MUSCLE.aln | grep Modeler | sed 's/Modeler//' >> MUSCLEModeler
done

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r ebola$i/trueData/ebolaTrueMSA.fasta -e ebola$i/ClustalOmega/Clustal.aln | grep Modeler | sed 's/Modeler//' >> ClustalModeler
done
