#!/usr/bin/env bash

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r ebola$i/trueData/ebolaTrueMSA.fasta -e ebola$i/MAFFT/MAFFT.aln | grep Compression | sed 's/Compression//' >> MAFFTCompression
done

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r ebola$i/trueData/ebolaTrueMSA.fasta -e ebola$i/MUSCLE/MUSCLE.aln | grep Compression | sed 's/Compression//' >> MUSCLECompression
done

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r ebola$i/trueData/ebolaTrueMSA.fasta -e ebola$i/ClustalOmega/Clustal.aln | grep Compression | sed 's/Compression//' >> ClustalCompression
done
