#!/usr/bin/env bash

for ((i=0; i < 10; i++))
do
    cd ebola$i/MAFFT/FastTree/RAxML
    rm -rf ebolaTrueMSA*
    cp ../../MAFFT.aln .
    raxml-ng --msa MAFFT.aln --model GTR+FO+I+R4 --evaluate --tree resolved.tre

    cd ../IQTree
    rm -rf ebolaTrueMSA*
    cp ../../MAFFT.aln .
    iqtree -m GTR+I+R -s MAFFT.aln -nt AUTO -te ../fast.tre

    cd ../IQTreeMFP
    rm -rf ebolaTrueMSA*
    cp ../../MAFFT.aln .
    iqtree -m MFP -s MAFFT.aln -nt AUTO -te ../fast.tre

    cd ../PhyML
    rm -rf ebolaTrueMSA*
    fasta2phylip.py -i ../../MAFFT.aln -o MAFFT.phy
    phyml -i MAFFT.phy -a e -d nt -m GTR --no_memory_check -o lr -u resolved.tre

    cd ../../../../
done

for ((i=0; i < 10; i++))
do
    cd ebola$i/MUSCLE/FastTree/RAxML
    rm -rf ebolaTrueMSA*
    cp ../../MUSCLE.aln .
    raxml-ng --msa MUSCLE.aln --model GTR+FO+I+R4 --evaluate --tree resolved.tre

    cd ../IQTree
    rm -rf ebolaTrueMSA*
    cp ../../MUSCLE.aln .
    iqtree -m GTR+I+R -s MUSCLE.aln -nt AUTO -te ../fast.tre

    cd ../IQTreeMFP
    rm -rf ebolaTrueMSA*
    cp ../../MUSCLE.aln .
    iqtree -m MFP -s MUSCLE.aln -nt AUTO -te ../fast.tre

    cd ../PhyML
    rm -rf ebolaTrueMSA*
    fasta2phylip.py -i ../../MUSCLE.aln -o MUSCLE.phy
    phyml -i MUSCLE.phy -a e -d nt -m GTR --no_memory_check -o lr -u resolved.tre

    cd ../../../../
done

for ((i=0; i < 10; i++))
do
    cd ebola$i/ClustalOmega/FastTree/RAxML
    rm -rf ebolaTrueMSA*
    cp ../../Clustal.aln .
    raxml-ng --msa Clustal.aln --model GTR+FO+I+R4 --evaluate --tree resolved.tre

    cd ../IQTree
    rm -rf ebolaTrueMSA*
    cp ../../Clustal.aln .
    iqtree -m GTR+I+R -s Clustal.aln -nt AUTO -te ../fast.tre

    cd ../IQTreeMFP
    rm -rf ebolaTrueMSA*
    cp ../../Clustal.aln .
    iqtree -m MFP -s Clustal.aln -nt AUTO -te ../fast.tre

    cd ../PhyML
    rm -rf ebolaTrueMSA*
    fasta2phylip.py -i ../../Clustal.aln -o Clustal.phy
    phyml -i Clustal.phy -a e -d nt -m GTR --no_memory_check -o lr -u resolved.tre

    cd ../../../../
done
