#!/usr/bin/env bash

for ((i=0; i < 10; i++))
do
    cd ebola$i/FastTree
    cat ../trueData/ebolaTrueMSA.fasta | FastTree -gamma -nt -gtr -out fast.tre

    cd ../IQTree
    cp ../trueData/ebolaTrueMSA.fasta .
    iqtree -m GTR+I+R -s ebolaTrueMSA.fasta -nt AUTO

    cd ../IQTreeMFP
    cp ../trueData/ebolaTrueMSA.fasta .
    iqtree -m MFT -s MAFFT.aln -nt AUTO

    cd ../RAxML
    cp ../trueData/ebolaTrueMSA.fasta .
    raxml-ng --msa ebolaTrueMSA.fasta --model GTR+I+G

    cd ../PhyML
    cp ../trueData/ebolaTrueMSA.phy .
    phyml -i ebolaTrueMSA.phy -a e -d nt -m GTR --no_memory_check

    cd ../../
done
