#!/usr/bin/env bash

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r hiv$i/trueData/hivTrueMSA.fasta -e hiv$i/MAFFT/MAFFT.aln | grep TC | sed 's/TC//' >> MAFFTTC
done

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r hiv$i/trueData/hivTrueMSA.fasta -e hiv$i/MUSCLE/MUSCLE.aln | grep TC | sed 's/TC//' >> MUSCLETC
done

for ((i=0; i < 10; i++))
do
    java -jar ../helperScripts/FastSP.jar -r hiv$i/trueData/hivTrueMSA.fasta -e hiv$i/ClustalOmega/Clustal.aln | grep TC | sed 's/TC//' >> ClustalTC
done
