#!/usr/bin/env bash

for ((i=0; i < 10; i++))
do
    cd hiv$i
    mkdir MUSCLE
    cd MUSCLE
    mkdir FastTree IQTree IQTreeMFP PhyML RAxML
    muscle -in ../hivSeqs.fas -out ./MUSCLE.aln
    
    cd FastTree
    cat ../MUSCLE.aln | FastTree -gamma -nt -gtr -out fast.tre

    cd ../IQTree
    cp ../MUSCLE.aln .
    iqtree -m GTR+I+R -s MUSCLE.aln -nt AUTO

    cd ../IQTreeMFP
    cp ../MUSCLE.aln .
    iqtree -m MFT -s MUSCLE.aln -nt AUTO

    cd ../RAxML
    cp ../MUSCLE.aln .
    raxml-ng --msa MUSCLE.aln --model GTR+I+G

    cd ../PhyML
    ../../../../helperScripts/fasta2phylip.py -i ../MUSCLE.aln -o ./MUSCLE.phy
    phyml -i MUSCLE.phy -a e -d nt -m GTR --no_memory_check

    cd ../../../
done
