#!/usr/bin/env bash

for ((i=0; i < 10; i++))
do
    cd hiv$i/FastTree
    cat ../trueData/hivTrueMSA.fasta | FastTree -gamma -nt -gtr -out fast.tre

    cd ../IQTree
    cp ../trueData/hivTrueMSA.fasta .
    iqtree -m GTR+I+R -s hivTrueMSA.fasta -nt AUTO

    cd ../IQTreeMFP
    cp ../trueData/hivTrueMSA.fasta .
    iqtree -m MFT -s hivTrueMSA.fasta -nt AUTO

    cd ../RAxML
    cp ../trueData/hivTrueMSA.fasta .
    raxml-ng --msa hivTrueMSA.fasta --model GTR+I+G

    cd ../PhyML
    cp ../trueData/hivTrueMSA.phy .
    phyml -i hivTrueMSA.phy -a e -d nt -m GTR --no_memory_check

    cd ../../
done
